/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convalidacion.pkg2.pkg0;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class Asignaturas extends javax.swing.JDialog {
    private String nombre="";
    private String idAsignatura="";
    private String nombreAsignatura="";
    
    /**
     * Creates new form Asignaturas
     */
    public Asignaturas(String nombre) {
        initComponents();
        this.nombre=nombre;
        mostrar();
        this.setTitle(nombre);
        this.setFocusable(false);
    }
    public void mostrar(){
      DefaultTableModel modelo=new DefaultTableModel();
      ResultSet rs2=Conectar.getTabla("select * from tb_asignaturas where id_universidad=(select id from tb_universidades where nombre_universidad like '%"+nombre+"%')");
      modelo.setColumnIdentifiers(new Object[]{"Asignaturas","Créditos","C. outcom","C. creditos","C. contenido","corresponde"});
      try{
            while(rs2.next()){
                 String x="no convalida";
                 
              if(rs2.getString("id_asignatura")!=null){
                ResultSet rs=Conectar.getTabla("select nombre_asignatura from tb_uneatlantico where id="+rs2.getInt("id_asignatura")+"");
                if(rs.next()){
                    x=rs.getString("nombre_asignatura");
                }
              
             // System.out.println("select nombre_asignatura from tb_uneatlantico where id='"+rs2.getString("id_asignatura")+"'");
              }
              modelo.addRow(new Object[]{rs2.getString("nombre_asignatura"),rs2.getString("creditos"),rs2.getBoolean("por_outcom") == true ? "Si":"No"  ,
                  rs2.getBoolean("por_creditos")== true ? "Si":"No",
                  rs2.getBoolean("por_contenido")== true ? "Si":"No",x});
            }
            rs2.close();
            Conectar.cerrarConec();
            jTable1.setModel(modelo);
      }catch(Exception e){
          System.out.println(e);
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTable1.getSelectedRow()>=0)
        {
            String comparar=jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5).toString();
            if(comparar.equals("no convalida")){
                JOptionPane.showMessageDialog(null,"esta asignatura no tiene similitudes con alguna asignatura nuestra");
            }
            else{
                try {
                    String t="";
                    Object p=String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0));
                    System.out.println(p);
                
                     nombreAsignatura=p.toString();
                    ResultSet rs=Conectar.getTabla("select u.id id from tb_asignaturas a, tb_uneatlantico u where a.nombre_asignatura = '"+p+"' and a.id_asignatura=u.id");
                if(rs.next()){
                    t=rs.getString("id");
                    System.err.println(t);
                    idAsignatura=t;
                }
                this.dispose();
                Comparacion b=new Comparacion(idAsignatura,nombreAsignatura,this.nombre);
                b.setLocationRelativeTo(null);
                b.setVisible(true);
            } catch (SQLException ex) {
                
                System.err.println(ex);
            }
        }
        }else{
        JOptionPane.showMessageDialog(null,"Selecciona alguna opcion");
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Asignaturas dialog = new Asignaturas("");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
